### PR TITLE
12 student profile management

### LINKED ISSUE #12: Student Profile management

### PR DESCRIPTION
**Pull request by YASSINEJR3**

### CODE REVIEW

**Review by w0l1d — DISMISSED** [review]

**Review by AbdoAitrais — CHANGES_REQUESTED** [review]
Why did you use a String for the dates in the Education and Experience Models :
    private String startDate;
    private String endDate;
And its better if u use startAt and endAt as a convention

**Comment by AbdoAitrais** [comment]
i meant startedAt and endedAt for more clarity

**Comment by w0l1d** [comment]
start and end dates are fixed

review it plz??
@AbdoAitrais

**Review by AbdoAitrais — DISMISSED** [review]
Good work Fellas !

**Review by w0l1d — DISMISSED** [review]

**Review by w0l1d — APPROVED** [review]

**Review by AbdoAitrais — APPROVED** [review]
Good Stuff !

**Pull request merged**
